version: '3.9'
services:

  postgres:
    image: postgres:latest
    restart: always
    ports:
    - 5432:5432
    volumes:
    - ${PWD}/postgres-data/:/var/lib/postgresql/data
    - ${PWD}/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: snackPackDb
      POSTGRES_USER: snack
      POSTGRES_PASSWORD: pack
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
    - 8080:80
    volumes:
    - ${PWD}/pgadmin-data:/var/lib/pgadmin
    links:
      - postgres:pgsql-server
    environment:
      PGADMIN_DEFAULT_EMAIL: snack@pack.com
      PGADMIN_DEFAULT_PASSWORD: pack
